// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using e_Parliament.DbContextApp;

#nullable disable

namespace e_Parliament.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250821110852_addActionsM-M")]
    partial class addActionsMM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("e_Parliament.models.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("account_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actions");

                    b.Property<string>("typeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.ToTable("account_types");
                });

            modelBuilder.Entity("e_Parliament.models.AccountTypeAction", b =>
                {
                    b.Property<int>("IdAccountType")
                        .HasColumnType("integer");

                    b.Property<int>("IdAction")
                        .HasColumnType("integer");

                    b.Property<int?>("AccountTypeId")
                        .HasColumnType("integer");

                    b.HasKey("IdAccountType", "IdAction");

                    b.HasIndex("AccountTypeId");

                    b.ToTable("AccountTypeAction");
                });

            modelBuilder.Entity("e_Parliament.models.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("commission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommissionName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("commission_name");

                    b.Property<int>("LegislatureId")
                        .HasColumnType("integer")
                        .HasColumnName("legislature_id");

                    b.HasKey("Id");

                    b.HasIndex("LegislatureId");

                    b.ToTable("commissions");
                });

            modelBuilder.Entity("e_Parliament.models.CommissionMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("commission_member_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionId")
                        .HasColumnType("integer")
                        .HasColumnName("id_commission");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_end");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_start");

                    b.Property<int>("ParliamentMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("parliament_member_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("CommissionId");

                    b.ToTable("commission_members");
                });

            modelBuilder.Entity("e_Parliament.models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("document_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("documentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.HasKey("Id");

                    b.HasIndex("documentType")
                        .IsUnique();

                    b.ToTable("document_types");
                });

            modelBuilder.Entity("e_Parliament.models.Legislature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("legislature_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("legislature_end");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("legislature_start");

                    b.HasKey("Id");

                    b.ToTable("legislatures");
                });

            modelBuilder.Entity("e_Parliament.models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("meeting_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionId")
                        .HasColumnType("integer")
                        .HasColumnName("commission_id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meeting_location");

                    b.Property<DateTime>("MeetingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("meeting_date");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meeting_subject");

                    b.HasKey("Id");

                    b.ToTable("meetings");
                });

            modelBuilder.Entity("e_Parliament.models.MeetingAtendace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("meeting_attendance_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MeetingId")
                        .HasColumnType("integer")
                        .HasColumnName("meeting_id");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("attendence_status");

                    b.Property<int>("parlamentar_id")
                        .HasColumnType("integer")
                        .HasColumnName("parlamentar_id");

                    b.HasKey("Id");

                    b.HasIndex("MeetingId");

                    b.ToTable("meeting_attendaces");
                });

            modelBuilder.Entity("e_Parliament.models.MeetingDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("meeting_document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionId")
                        .HasColumnType("integer")
                        .HasColumnName("commission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_name");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("document_type_id");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<int>("MeetingId")
                        .HasColumnType("integer")
                        .HasColumnName("meeting_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("MeetingId");

                    b.ToTable("meeting_documents");
                });

            modelBuilder.Entity("e_Parliament.models.ParlamentarGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("parlamentar_group_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ParlamentarGroupName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parlamentar_group_name");

                    b.HasKey("Id");

                    b.ToTable("parlamentar_groups");
                });

            modelBuilder.Entity("e_Parliament.models.ParlamentarGroupMembers", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id_parlamentar_group");

                    b.Property<int>("IdMembers")
                        .HasColumnType("integer")
                        .HasColumnName("member_group_id");

                    b.Property<int>("Id_legislature")
                        .HasColumnType("integer")
                        .HasColumnName("legislature_id");

                    b.HasKey("Id", "IdMembers");

                    b.HasIndex("IdMembers");

                    b.ToTable("parlamentar_group_members");
                });

            modelBuilder.Entity("e_Parliament.models.Parliamentarian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("parliamentarian_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("id_room_type");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("parliamentarians");
                });

            modelBuilder.Entity("e_Parliament.models.ParliamentariansMember", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("parlamentar_id");

                    b.Property<int>("IdCommissionMembers")
                        .HasColumnType("integer")
                        .HasColumnName("commission_members_id");

                    b.HasKey("Id", "IdCommissionMembers");

                    b.HasIndex("IdCommissionMembers");

                    b.ToTable("parliamentarians_members");
                });

            modelBuilder.Entity("e_Parliament.models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("room_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoomTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_type_name");

                    b.HasKey("Id");

                    b.ToTable("room_types");
                });

            modelBuilder.Entity("e_Parliament.models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("account_type_id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_password");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("e_Parliament.models.AccountTypeAction", b =>
                {
                    b.HasOne("e_Parliament.models.AccountType", null)
                        .WithMany("AccountTypeActions")
                        .HasForeignKey("AccountTypeId");
                });

            modelBuilder.Entity("e_Parliament.models.Commission", b =>
                {
                    b.HasOne("e_Parliament.models.Legislature", "IdLegislature")
                        .WithMany()
                        .HasForeignKey("LegislatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdLegislature");
                });

            modelBuilder.Entity("e_Parliament.models.CommissionMember", b =>
                {
                    b.HasOne("e_Parliament.models.Commission", "Commission")
                        .WithMany()
                        .HasForeignKey("CommissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commission");
                });

            modelBuilder.Entity("e_Parliament.models.MeetingAtendace", b =>
                {
                    b.HasOne("e_Parliament.models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("e_Parliament.models.MeetingDocument", b =>
                {
                    b.HasOne("e_Parliament.models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_Parliament.models.Meeting", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("e_Parliament.models.ParlamentarGroupMembers", b =>
                {
                    b.HasOne("e_Parliament.models.ParlamentarGroup", "Members")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_Parliament.models.CommissionMember", "CommissionMember")
                        .WithMany()
                        .HasForeignKey("IdMembers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommissionMember");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("e_Parliament.models.Parliamentarian", b =>
                {
                    b.HasOne("e_Parliament.models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("e_Parliament.models.ParliamentariansMember", b =>
                {
                    b.HasOne("e_Parliament.models.Parliamentarian", "Parliamentarian")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("e_Parliament.models.CommissionMember", "CommissionMember")
                        .WithMany()
                        .HasForeignKey("IdCommissionMembers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommissionMember");

                    b.Navigation("Parliamentarian");
                });

            modelBuilder.Entity("e_Parliament.models.Users", b =>
                {
                    b.HasOne("e_Parliament.models.AccountType", "AccountType")
                        .WithMany("Users")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("e_Parliament.models.AccountType", b =>
                {
                    b.Navigation("AccountTypeActions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
